// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NTag: typeof import('naive-ui')['NTag']
  }
}
